### ISSUE TITLE
Gemfile.lock causes error

### ISSUE THREAD

**Issue by andregmoeller** [innoq/SCS#38]
After making some changes I wanted to look at the changes at http://0.0.0.0:4000/. So, I ran `docker run -v "$PWD":/usr/src/app -p "4000:4000" starefossen/github-pages`. Running this command caused the following error:
```
% docker run -v "$PWD":/usr/src/app -p "4000:4000" starefossen/github-pages
Unable to find image 'starefossen/github-pages:latest' locally
latest: Pulling from starefossen/github-pages
911c6d0c7995: Pull complete 
66c75bb6a8fc: Pull complete 
a1d8100f3d6a: Pull complete 
640ab4473371: Pull complete 
0965307349c7: Pull complete 
5a58628acff1: Pull complete 
615f9e5a42c3: Pull complete 
Digest: sha256:5097d63b50e7a894b694761ded6ace912aa901b98f283824801db649ddb37684
Status: Downloaded newer image for starefossen/github-pages:latest
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/lockfile_parser.rb:108:in `warn_for_outdated_bundler_version': You must use Bundler 2 or greater with this lockfile. (Bundler::LockfileError)
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/lockfile_parser.rb:95:in `initialize'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/definition.rb:84:in `new'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/definition.rb:84:in `initialize'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/dsl.rb:218:in `new'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/dsl.rb:218:in `to_definition'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/dsl.rb:13:in `evaluate'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/definition.rb:35:in `build'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler.rb:135:in `definition'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler.rb:101:in `setup'
	from /usr/local/bundle/gems/jekyll-3.8.5/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
	from /usr/local/bundle/gems/jekyll-3.8.5/exe/jekyll:11:in `<top (required)>'
	from /usr/local/bundle/bin/jekyll:23:in `load'
	from /usr/local/bundle/bin/jekyll:23:in `<main>'
```

After I have removed the Gemfile.lock, I am able to run `docker run -v "$PWD":/usr/src/app -p "4000:4000" starefossen/github-pages` successfully.

**Comment by ewolff** [comment]
Thanks. This is a know issue, see https://github.com/Starefossen/docker-github-pages/issues/68 . I removed the `Gemfile.lock` file and verified it works.
